// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjeUovcglHAsh1a0zP3pG2m7Onj9okpJ8',
    appId: '1:55491109524:web:d85e5a474e29a71c228a81',
    messagingSenderId: '55491109524',
    projectId: 'erumobileapp',
    authDomain: 'erumobileapp.firebaseapp.com',
    storageBucket: 'erumobileapp.firebasestorage.app',
    measurementId: 'G-28VPHLT89Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgWdIcWh_RmMzE-CHj-gCTiOUSYzC7rS8',
    appId: '1:55491109524:android:fece4ebcb5a6bfeb228a81',
    messagingSenderId: '55491109524',
    projectId: 'erumobileapp',
    storageBucket: 'erumobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc5Rog73znTlo1wbagGguAxV-MjKyqpHY',
    appId: '1:55491109524:ios:bd56bff1c9f0ad15228a81',
    messagingSenderId: '55491109524',
    projectId: 'erumobileapp',
    storageBucket: 'erumobileapp.firebasestorage.app',
    iosBundleId: 'com.example.oruEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc5Rog73znTlo1wbagGguAxV-MjKyqpHY',
    appId: '1:55491109524:ios:bd56bff1c9f0ad15228a81',
    messagingSenderId: '55491109524',
    projectId: 'erumobileapp',
    storageBucket: 'erumobileapp.firebasestorage.app',
    iosBundleId: 'com.example.oruEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjeUovcglHAsh1a0zP3pG2m7Onj9okpJ8',
    appId: '1:55491109524:web:de0401b452e67dc1228a81',
    messagingSenderId: '55491109524',
    projectId: 'erumobileapp',
    authDomain: 'erumobileapp.firebaseapp.com',
    storageBucket: 'erumobileapp.firebasestorage.app',
    measurementId: 'G-Q9QH2NT24D',
  );
}
